import Foundation

/// 内置动作细分肌群 + 要点数据（任务 2.x 回填）。code -> (主动肌, 协同肌, 要点)。
/// 均为运动解剖客观事实 + 原创要点短句，无版权敏感数据。
extension BuiltinExercise {
    static let regionData: [String: (primary: [MuscleRegion], secondary: [MuscleRegion], cues: [String])] = [
        "BB_BENCH_PRESS": ([.chest], [.deltFront, .triceps], ["肩胛后缩下沉，全程贴凳", "杠铃落乳线下沿，前臂垂直", "推起胸主导，肘不外展过度"]),
        "DB_BENCH_PRESS": ([.chest], [.deltFront, .triceps], ["两哑铃落至胸侧略低位", "顶峰内夹挤压胸肌", "手腕中立，肘下藏不外翻"]),
        "INCLINE_BB_PRESS": ([.chest], [.deltFront, .triceps], ["凳角30到45度即可", "杠铃落锁骨下沿", "发力推向上胸而非肩"]),
        "INCLINE_DB_PRESS": ([.chest], [.deltFront, .triceps], ["上斜30度找上胸发力感", "下放至上胸两侧充分伸展", "顶端不锁死，保持张力"]),
        "DECLINE_BB_PRESS": ([.chest], [.deltFront, .triceps], ["下斜角度找下胸", "杠铃落乳线下方", "保持核心稳，腿别乱蹬"]),
        "DECLINE_DB_PRESS": ([.chest], [.deltFront, .triceps], ["下斜位强化下胸", "哑铃轨迹略向脚侧", "顶峰挤压再缓慢下放"]),
        "SMITH_BENCH_PRESS": ([.chest], [.deltFront, .triceps], ["躺位调到杠落乳线", "肩胛后缩稳定肩带", "轨道固定，专注胸发力"]),
        "MACHINE_CHEST_PRESS": ([.chest], [.deltFront, .triceps], ["握把对齐乳线高度", "推到位不锁肘", "回放控制，胸保持张力"]),
        "CABLE_FLY": ([.chest], [.deltFront], ["微屈肘固定不变角", "向身体中线划弧合拢", "顶峰挤压一秒再控放"]),
        "HIGH_CABLE_FLY": ([.chest], [.deltFront], ["滑轮置高位向下夹", "终点双手交叠找下胸", "肘微屈全程不变"]),
        "LOW_CABLE_FLY": ([.chest], [.deltFront], ["滑轮置低位向上合", "轨迹向上夹找上胸", "顶峰挤压控制下放"]),
        "DB_FLY": ([.chest], [.deltFront], ["微屈肘画大弧下放", "感受胸部充分伸展", "起回胸主导别变推"]),
        "INCLINE_DB_FLY": ([.chest], [.deltFront], ["上斜位强化上胸", "下放至胸两侧拉伸", "顶端内夹不碰铃"]),
        "PEC_DECK": ([.chest], [.deltFront], ["前臂贴垫推动", "向中线合拢挤压胸", "肩胛后缩别耸肩"]),
        "CHEST_DIP": ([.chest], [.triceps, .deltFront], ["身体前倾找下胸", "下放至肩略低于肘", "推起挺胸别耸肩"]),
        "PUSH_UP": ([.chest], [.triceps, .deltFront, .abs], ["身体绷直成一条线", "下放胸近地肘约45度", "推起核心收紧不塌腰"]),
        "INCLINE_PUSH_UP": ([.chest], [.triceps, .deltFront], ["手撑高位降低难度", "身体保持笔直", "下放控制推起有力"]),
        "DECLINE_PUSH_UP": ([.chest], [.triceps, .deltFront], ["脚垫高强化上胸", "核心收紧不塌腰", "下放胸近地控制节奏"]),
        "DIAMOND_PUSH_UP": ([.triceps], [.chest, .deltFront], ["双手成菱形于胸下", "肘贴身向后", "下放至手再撑起"]),
        "MACHINE_INCLINE_PRESS": ([.chest], [.deltFront, .triceps], ["座椅调至握把对上胸", "推起不锁肘", "回放控制保持张力"]),
        "SVEND_PRESS": ([.chest], [.deltFront], ["两片杠铃掌心夹紧", "向前平推全程内夹", "回收保持挤压感"]),
        "PULL_UP": ([.lats], [.biceps, .deltRear, .forearms], ["肩胛先下沉再启动", "拉到下巴过杠", "下放控制至手臂伸直"]),
        "CHIN_UP": ([.lats], [.biceps, .forearms], ["反握肩宽更顾二头", "挺胸拉胸口近杠", "下放全程控制"]),
        "WIDE_PULL_UP": ([.lats], [.deltRear, .biceps, .forearms], ["宽握强化背阔外侧", "拉时肘向下后收", "避免借力摆荡"]),
        "LAT_PULLDOWN": ([.lats], [.biceps, .deltRear], ["挺胸下拉至锁骨", "肘下沉带动而非手臂", "缓慢回放感受拉伸"]),
        "CLOSE_LAT_PULLDOWN": ([.lats], [.biceps, .forearms], ["窄握找背阔下部", "肘贴身向下拉", "顶峰挤背再控放"]),
        "STRAIGHT_ARM_PULLDOWN": ([.lats], [.triceps], ["直臂微屈固定", "用背把杆压向大腿", "全程感受背阔收缩"]),
        "BB_ROW": ([.lats], [.traps, .biceps, .lowerBack, .deltRear], ["俯身约45度背挺直", "杠拉向下腹肘后收", "顶峰挤背别甩腰"]),
        "PENDLAY_ROW": ([.lats], [.traps, .biceps, .lowerBack], ["每次起于地面静止", "爆发拉向下胸", "背平不弓，落地复位"]),
        "T_BAR_ROW": ([.lats], [.traps, .biceps, .deltRear], ["俯身夹紧把手", "拉向腹部肘贴身", "顶峰挤背控制下放"]),
        "DB_ROW": ([.lats], [.traps, .biceps, .deltRear], ["单手撑凳背平", "哑铃拉向髋侧", "肘后收挤背别转体"]),
        "CHEST_SUPPORTED_ROW": ([.lats], [.traps, .deltRear, .biceps], ["胸贴斜凳消除借力", "两铃拉向腰侧", "顶峰夹背缓慢放"]),
        "SEATED_CABLE_ROW": ([.lats], [.traps, .biceps, .deltRear], ["挺胸坐直微前倾", "拉把至腹肘贴身", "顶峰挤背回放伸展"]),
        "MACHINE_ROW": ([.lats], [.traps, .biceps, .deltRear], ["胸靠垫调握把", "拉向身体挤背", "回放控制保持张力"]),
        "INVERTED_ROW": ([.lats], [.biceps, .traps, .deltRear], ["身体绷直成斜线", "胸拉向杠肘后收", "全程核心收紧"]),
        "DEADLIFT": ([.lats, .lowerBack], [.glutes, .hams, .traps, .forearms], ["杠贴胫骨背挺直", "髋膝同步伸展起身", "顶端站直勿后仰"]),
        "RACK_PULL": ([.lowerBack], [.glutes, .traps, .lats, .forearms], ["杠起于膝附近", "髋后坐背挺直", "伸髋锁定挤臀"]),
        "DB_PULLOVER": ([.lats], [.chest, .triceps], ["仰卧哑铃过顶下放", "感受背阔拉伸", "用背把铃拉回胸上"]),
        "BACK_EXTENSION": ([.lowerBack], [.glutes, .hams], ["髋为支点下俯", "起身至身体成直线", "顶端别过伸腰椎"]),
        "GOOD_MORNING": ([.lowerBack], [.hams, .glutes], ["杠置上背髋后推", "背全程挺直", "感受腘绳拉伸再起"]),
        "SHRUG_BB": ([.traps], [.forearms], ["直臂垂杠耸肩向上", "肩往耳朵方向提", "顶峰停顿别转圈"]),
        "SHRUG_DB": ([.traps], [.forearms], ["两哑铃垂体侧", "纯耸肩向上", "顶峰挤压控制下放"]),
        "MEADOWS_ROW": ([.lats], [.traps, .biceps, .deltRear], ["侧身握杠端单臂拉", "肘高拉向髋后", "挤背控制别耸肩"]),
        "KROC_ROW": ([.lats], [.traps, .biceps, .forearms], ["大重量高次单臂划", "允许轻微借力", "肘后收拉满幅度"]),
        "ASSISTED_PULL_UP": ([.lats], [.biceps, .deltRear, .forearms], ["膝跪垫上获助力", "肩胛下沉启动", "拉至下巴过杠控放"]),
        "OHP": ([.deltFront], [.triceps, .traps], ["收紧核心臀夹紧", "杠过头略后送至耳上", "推起别过度后仰"]),
        "SEATED_BB_PRESS": ([.deltFront], [.triceps, .traps], ["靠背坐稳收核心", "杠从锁骨推过头", "下放至下巴高度"]),
        "DB_SHOULDER_PRESS": ([.deltFront], [.triceps, .traps], ["哑铃起于耳侧", "向上推略内合", "下放至耳高控制"]),
        "ARNOLD_PRESS": ([.deltFront], [.triceps, .traps], ["起始掌心朝己", "上推同时旋腕外翻", "顶端掌心朝前"]),
        "MACHINE_SHOULDER_PRESS": ([.deltFront], [.triceps, .traps], ["座椅调至握把齐肩", "推起不锁肘", "回放控制保持张力"]),
        "LANDMINE_PRESS": ([.deltFront], [.triceps, .chest], ["单手托杠端于肩前", "斜向上推送", "核心收紧别歪身"]),
        "PIKE_PUSH_UP": ([.deltFront], [.triceps], ["臀高耸成倒V", "头顶向地下放", "撑起肩主导发力"]),
        "LATERAL_RAISE": ([.deltFront], [], ["微屈肘提向两侧", "至与肩平即可", "小指略高别耸肩"]),
        "CABLE_LATERAL_RAISE": ([.deltFront], [], ["绳索置低位侧拉", "全程恒定张力", "提至肩平控制下放"]),
        "FRONT_RAISE": ([.deltFront], [], ["哑铃前平举至肩高", "微屈肘别摆动", "缓慢下放控制"]),
        "CABLE_FRONT_RAISE": ([.deltFront], [], ["绳索低位向前抬", "提至肩高即停", "回放保持张力"]),
        "REAR_DELT_FLY": ([.deltRear], [.traps], ["俯身背平微屈肘", "向两侧后展画弧", "顶峰挤后束别耸肩"]),
        "REVERSE_PEC_DECK": ([.deltRear], [.traps], ["胸贴垫握把", "向后外展打开", "顶峰夹后束控放"]),
        "FACE_PULL": ([.deltRear], [.traps], ["绳索置面部高度", "拉向脸肘高于腕", "外旋打开挤后束"]),
        "UPRIGHT_ROW": ([.deltFront], [.traps, .biceps], ["杠贴身提向锁骨", "肘领先高于腕", "别拉太高护肩"]),
        "DB_UPRIGHT_ROW": ([.deltFront], [.traps, .biceps], ["两哑铃贴身上提", "肘外展领先", "提至胸高控制下放"]),
        "BTN_PRESS": ([.deltFront], [.triceps, .traps], ["杠下放至颈后", "肩活动好者再做", "推起核心收紧"]),
        "MACHINE_LATERAL_RAISE": ([.deltFront], [], ["上臂贴垫向外推", "至肩平即停", "回放控制不松垮"]),
        "BB_CURL": ([.biceps], [.forearms], ["肘固定贴体侧", "弯举至顶峰挤压", "下放至臂直控制"]),
        "EZ_BAR_CURL": ([.biceps], [.forearms], ["斜握减腕压", "肘定弯举", "顶峰收紧缓放"]),
        "DB_CURL": ([.biceps], [.forearms], ["掌心向上弯举", "肘别前移", "顶峰挤压控制下放"]),
        "HAMMER_CURL": ([.biceps], [.forearms], ["掌心相对中立握", "弯举至顶峰", "强化肱桡肌别甩"]),
        "INCLINE_DB_CURL": ([.biceps], [.forearms], ["靠斜凳臂自然垂", "起点充分拉伸二头", "弯举肘别前移"]),
        "CONCENTRATION_CURL": ([.biceps], [], ["肘抵大腿内侧", "专注弯举挤峰", "缓慢下放孤立二头"]),
        "SPIDER_CURL": ([.biceps], [], ["俯靠斜凳臂垂直", "弯举至顶峰", "全程消除借力"]),
        "PREACHER_CURL": ([.biceps], [.forearms], ["大臂贴牧师垫", "下放至近伸直", "弯举挤峰别离垫"]),
        "CABLE_CURL": ([.biceps], [.forearms], ["绳索恒定张力弯举", "肘固定身侧", "顶峰挤压控制回放"]),
        "MACHINE_CURL": ([.biceps], [], ["大臂贴垫弯举", "顶峰挤压", "回放控制不松"]),
        "TRICEP_PUSHDOWN": ([.triceps], [], ["肘夹身侧固定", "下压至臂伸直", "顶峰挤三头缓回"]),
        "ROPE_PUSHDOWN": ([.triceps], [], ["绳柄下压末端外分", "肘贴身不前移", "伸直挤压控制回"]),
        "SKULL_CRUSHER": ([.triceps], [], ["大臂垂直不动", "杠下放至额后", "仅伸肘起回"]),
        "CLOSE_GRIP_BENCH": ([.triceps], [.chest, .deltFront], ["握略窄于肩", "肘贴身下放", "推起三头主导"]),
        "OVERHEAD_TRICEP_EXT": ([.triceps], [], ["哑铃过顶大臂垂直", "下放至颈后伸展", "伸肘起回别晃大臂"]),
        "CABLE_OVERHEAD_EXT": ([.triceps], [], ["背对绳索过顶前伸", "大臂固定伸肘", "感受三头长头拉伸"]),
        "TRICEP_KICKBACK": ([.triceps], [], ["俯身大臂贴体平举", "向后伸肘至直", "顶峰挤压缓回"]),
        "TRICEP_DIP": ([.triceps], [.chest, .deltFront], ["身体保持直立", "下放至肘约90度", "推起三头主导"]),
        "BENCH_DIP": ([.triceps], [.deltFront], ["手撑凳沿臀离凳", "屈肘下放身体", "伸肘撑起别耸肩"]),
        "MACHINE_TRICEP_EXT": ([.triceps], [], ["肘固定贴垫", "伸肘至直挤压", "回放控制保持张力"]),
        "WRIST_CURL": ([.forearms], [], ["前臂贴腿掌心向上", "腕向上卷起", "缓慢下放充分屈伸"]),
        "REVERSE_WRIST_CURL": ([.forearms], [], ["掌心向下前臂固定", "腕向上抬起", "控制下放练伸腕肌"]),
        "ZOTTMAN_CURL": ([.biceps], [.forearms], ["上举掌心向上", "顶端旋腕掌心朝下", "翻握下放练前臂"]),
        "REVERSE_CURL": ([.forearms], [.biceps], ["正握掌心向下弯举", "肘固定身侧", "顶峰挤肱桡肌"]),
        "JM_PRESS": ([.triceps], [.chest], ["窄握杠下放至下巴", "肘前移混合卧推弯举", "伸肘推起三头主导"]),
        "BB_SQUAT": ([.quads], [.glutes, .hams, .lowerBack, .adductors], ["杠置上背核心绷紧", "髋膝同屈蹲至大腿平", "膝随脚尖蹬地起"]),
        "FRONT_SQUAT": ([.quads], [.glutes, .lowerBack, .abs], ["杠托锁骨肘高抬", "上身竖直下蹲", "核心顶住别塌"]),
        "SMITH_SQUAT": ([.quads], [.glutes, .hams], ["脚略前置稳轨道", "下蹲至大腿平", "蹬地起膝不内扣"]),
        "HACK_SQUAT": ([.quads], [.glutes], ["背贴垫脚中置", "下蹲深至大腿平", "蹬起膝随脚尖"]),
        "GOBLET_SQUAT": ([.quads], [.glutes, .adductors], ["哑铃抱胸前", "上身直深蹲", "肘内侧轻触膝"]),
        "LEG_PRESS": ([.quads], [.glutes, .hams], ["脚与肩同宽踏板", "下放膝向胸不锁腰", "蹬起膝别锁死"]),
        "LEG_EXTENSION": ([.quads], [], ["脚踝抵垫", "伸膝至直挤股四", "缓慢下放控制"]),
        "BULGARIAN_SPLIT_SQUAT": ([.quads], [.glutes, .hams, .adductors], ["后脚搭凳前脚承重", "垂直下蹲膝过脚", "前脚跟蹬地起"]),
        "LUNGE": ([.quads], [.glutes, .hams], ["跨步下蹲双膝90度", "上身直核心稳", "前脚跟发力回"]),
        "WALKING_LUNGE": ([.quads], [.glutes, .hams], ["交替向前迈步下蹲", "膝不内扣不超脚尖太多", "重心稳推进"]),
        "STEP_UP": ([.quads], [.glutes, .hams], ["全脚踩稳箱面", "前腿发力登上", "控制下落别砸"]),
        "SISSY_SQUAT": ([.quads], [], ["身体后倾膝前移", "脚跟抬感受股四拉伸", "核心收紧控制起回"]),
        "PISTOL_SQUAT": ([.quads], [.glutes, .hams, .abs], ["单腿下蹲另腿前伸", "全程平衡控制", "脚跟蹬地起立"]),
        "LEG_CURL": ([.hams], [.calves], ["俯卧脚踝抵垫", "屈膝勾至臀", "缓慢下放控制"]),
        "SEATED_LEG_CURL": ([.hams], [.calves], ["坐姿腿垫压腘下", "屈膝向下勾", "顶峰挤压控制回"]),
        "ROMANIAN_DL": ([.hams], [.glutes, .lowerBack], ["髋后推杠贴腿下滑", "背挺膝微屈", "感受腘绳拉伸再伸髋"]),
        "DB_RDL": ([.hams], [.glutes, .lowerBack], ["哑铃贴腿髋后坐", "背平膝微屈", "腘绳拉满再挺髋"]),
        "STIFF_LEG_DL": ([.hams], [.glutes, .lowerBack], ["膝近伸直髋铰链", "杠贴腿下放", "感受腘绳拉伸起身"]),
        "NORDIC_CURL": ([.hams], [.calves], ["跪姿固定脚踝", "身体缓慢前倾", "腘绳离心抗住下放"]),
        "STANDING_CALF_RAISE": ([.calves], [], ["前脚掌踩台", "提踵至最高", "下放充分拉伸"]),
        "SEATED_CALF_RAISE": ([.calves], [], ["膝下压垫前掌踩台", "提踵挤压比目鱼肌", "缓慢下放全幅"]),
        "DB_CALF_RAISE": ([.calves], [], ["手持哑铃前掌踩台", "提踵至顶峰", "控制下放别弹"]),
        "HIP_ADDUCTION": ([.adductors], [], ["腿垫置膝内侧", "向内合拢挤压", "缓慢外放控制"]),
        "HIP_ABDUCTION": ([.glutes], [], ["腿垫置膝外侧", "向外展开打开髋", "顶峰挤臀控制回"]),
        "BOX_SQUAT": ([.quads], [.glutes, .hams, .lowerBack], ["髋后坐轻触箱", "不放松反弹起", "蹬地伸髋膝"]),
        "GLUTE_HAM_RAISE": ([.hams], [.glutes, .calves], ["脚踝固定膝跪垫", "身体下放伸展", "腘绳臀发力起身"]),
        "DONKEY_CALF_RAISE": ([.calves], [], ["俯身髋负重前掌踩台", "提踵至顶", "下放充分拉伸"]),
        "HIP_THRUST": ([.glutes], [.hams, .quads], ["上背靠凳杠置髋", "伸髋顶起至躯干平", "顶峰夹臀别过伸腰"]),
        "BB_GLUTE_BRIDGE": ([.glutes], [.hams], ["仰卧杠置髋部", "伸髋顶起夹臀", "下放控制别塌腰"]),
        "SINGLE_LEG_HIP_THRUST": ([.glutes], [.hams], ["单腿支撑顶髋", "另腿屈抬稳定", "顶峰夹臀控制下放"]),
        "CABLE_KICKBACK": ([.glutes], [.hams], ["绳套脚踝向后蹬", "伸髋挤臀", "控制回收别甩"]),
        "GLUTE_KICKBACK_MACHINE": ([.glutes], [.hams], ["脚踏板向后蹬", "伸髋顶峰挤臀", "缓慢回放保持张力"]),
        "SUMO_DEADLIFT": ([.glutes], [.quads, .hams, .lowerBack, .adductors], ["宽站脚尖外展", "膝随脚尖下握杠", "伸髋膝同步起身"]),
        "SUMO_SQUAT": ([.glutes], [.quads, .adductors, .hams], ["宽站脚尖外展", "竖直下蹲膝随脚", "蹬起挤臀夹内收"]),
        "CURTSY_LUNGE": ([.glutes], [.quads, .hams, .adductors], ["后腿斜向后交叉下蹲", "前膝随脚尖", "前脚跟蹬地回"]),
        "FROG_PUMP": ([.glutes], [.hams], ["仰卧脚掌相对外展", "伸髋顶起夹臀", "高次找泵感"]),
        "KETTLEBELL_SWING": ([.glutes], [.hams, .lowerBack, .deltFront], ["髋铰链后摆壶铃", "爆发伸髋甩至肩高", "靠髋驱动非手臂"]),
        "PLANK": ([.abs], [.obliques, .lowerBack], ["肘肩同宽身成直线", "收紧核心夹臀", "别塌腰别耸臀"]),
        "SIDE_PLANK": ([.obliques], [.abs], ["单肘撑身侧成直线", "髋抬高保持稳定", "别前后晃别塌髋"]),
        "HANGING_LEG_RAISE": ([.abs], [.obliques, .forearms], ["悬垂别摆荡", "卷骨盆抬直腿至水平上", "控制下放收腹主导"]),
        "HANGING_KNEE_RAISE": ([.abs], [.obliques, .forearms], ["悬垂屈膝上提", "卷骨盆收腹", "控制下放别借力"]),
        "LEG_RAISE": ([.abs], [.obliques], ["仰卧下背贴地", "直腿抬至垂直", "下放控制别离地反弓"]),
        "CRUNCH": ([.abs], [], ["仰卧屈膝手扶头", "卷起肩离地收腹", "别用力扯脖子"]),
        "CABLE_CRUNCH": ([.abs], [], ["跪姿绳柄置头侧", "卷腹弓背向下", "髋固定靠腹收缩"]),
        "BICYCLE_CRUNCH": ([.obliques], [.abs], ["交替肘碰对侧膝", "转体由腹斜肌带", "下背贴地慢做"]),
        "V_UP": ([.abs], [.obliques], ["仰卧手脚同时抬", "身体折成V触脚", "控制下放别砸地"]),
        "RUSSIAN_TWIST": ([.obliques], [.abs], ["坐姿后倾脚抬", "左右转体触地", "由腰腹带动旋转"]),
        "AB_WHEEL": ([.abs], [.obliques, .lowerBack, .lats], ["跪姿轮向前推出", "核心收紧别塌腰", "腹发力收回"]),
        "MOUNTAIN_CLIMBER": ([.abs], [.obliques, .quads], ["撑姿身体绷直", "交替提膝向胸", "髋别上下乱晃"]),
        "DEAD_BUG": ([.abs], [.obliques], ["仰卧下背贴地", "对侧手脚同伸", "全程腰别离地"]),
        "WOODCHOPPER": ([.obliques], [.abs], ["绳索斜向跨身拉", "转体由核心带", "手臂只是传力"]),
        "PALLOF_PRESS": ([.obliques], [.abs], ["侧对绳索推向前", "抗旋别让身转", "核心收紧稳住"]),
        "TOE_TOUCH": ([.abs], [], ["仰卧腿垂直上举", "卷肩起手摸脚", "靠腹收缩别甩手"]),
        "FLUTTER_KICK": ([.abs], [.obliques], ["仰卧下背贴地", "直腿小幅交替踢", "全程收腹别反弓"]),
        "HOLLOW_HOLD": ([.abs], [.obliques], ["仰卧手脚抬离地", "下背压地成船形", "收紧核心稳住别晃"]),
        "POWER_CLEAN": ([.traps, .quads], [.glutes, .hams, .lowerBack, .deltFront], ["杠贴身爆发伸髋", "耸肩提肘高拉", "屈膝接铃于肩前"]),
        "HANG_CLEAN": ([.traps, .quads], [.glutes, .hams, .deltFront], ["起于髋膝悬垂位", "爆发伸髋上拉", "下潜接铃稳定"]),
        "CLEAN_AND_JERK": ([.quads, .deltFront], [.glutes, .hams, .traps, .triceps, .lowerBack], ["翻铃至肩前架住", "屈膝借腿驱动上挺", "分腿稳定锁定过头"]),
        "SNATCH": ([.deltFront, .traps], [.glutes, .hams, .quads, .lowerBack, .triceps], ["宽握杠爆发伸髋", "高拉下潜一气呵成", "过头锁定稳接"]),
        "THRUSTER": ([.quads, .deltFront], [.glutes, .triceps, .traps], ["前蹲到底", "起身借力上推过头", "蹲推连贯一气"]),
        "KB_CLEAN": ([.traps, .glutes], [.hams, .quads, .deltFront, .forearms], ["髋驱动上摆壶铃", "翻转贴前臂落架位", "别砸手腕轻接"]),
        "KB_SNATCH": ([.deltFront, .glutes], [.hams, .traps, .quads, .forearms], ["髋爆发上摆", "翻腕穿过锁定过头", "下放控制回摆"]),
        "TURKISH_GET_UP": ([.abs], [.deltFront, .obliques, .glutes, .quads], ["举铃锁肩始终对位", "分步起身眼盯铃", "缓慢控制逆序回"]),
        "BURPEE": ([.quads], [.chest, .triceps, .abs, .glutes], ["俯身撑地后蹬腿", "俯卧撑后收腿", "爆发跳起伸展"]),
        "FARMER_CARRY": ([.forearms, .traps], [.abs, .obliques, .glutes, .quads], ["重铃握紧挺胸走", "核心收紧躯干稳", "小步快走别晃"]),
    ]
}
